import { saveAs } from 'file-saver';
import { Document, Paragraph, TextRun, Packer } from 'docx';

/**
 * 复制文本到剪贴板
 */
export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
};

/**
 * 导出为 TXT 文件
 */
export const exportAsTxt = (text: string, filename: string = 'simplified-text.txt'): void => {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, filename);
};

/**
 * 导出为 Markdown 文件
 */
export const exportAsMarkdown = (
  originalText: string,
  simplifiedText: string,
  filename: string = 'simplified-text.md'
): void => {
  const markdown = `# Text Simplification Result

## Original Text

${originalText}

## Simplified Text

${simplifiedText}

---
*Generated by Text Simplifier*
`;
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  saveAs(blob, filename);
};

/**
 * 导出为 DOCX 文件
 */
export const exportAsDocx = async (
  originalText: string,
  simplifiedText: string,
  filename: string = 'simplified-text.docx'
): Promise<void> => {
  try {
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Text Simplification Result',
                  bold: true,
                  size: 32,
                }),
              ],
            }),
            new Paragraph({ text: '' }), // Empty line
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Original Text',
                  bold: true,
                  size: 28,
                }),
              ],
            }),
            new Paragraph({ text: originalText }),
            new Paragraph({ text: '' }), // Empty line
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Simplified Text',
                  bold: true,
                  size: 28,
                }),
              ],
            }),
            new Paragraph({ text: simplifiedText }),
            new Paragraph({ text: '' }), // Empty line
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Generated by Text Simplifier',
                  italics: true,
                  size: 20,
                }),
              ],
            }),
          ],
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, filename);
  } catch (error) {
    console.error('Failed to export as DOCX:', error);
    throw error;
  }
};

/**
 * 计算字符数
 */
export const countCharacters = (text: string): number => {
  return text.length;
};

/**
 * 计算字数
 */
export const countWords = (text: string): number => {
  return text.trim().split(/\s+/).filter(Boolean).length;
};

/**
 * 格式化关键词（去除空格，返回数组）
 */
export const formatKeywords = (keywords: string): string[] => {
  return keywords
    .split(',')
    .map((k) => k.trim())
    .filter(Boolean);
};
